/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiStoryServerRouteImport } from './routes/api.story'
import { ServerRoute as ApiImageServerRouteImport } from './routes/api.image'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryServerRoute = ApiStoryServerRouteImport.update({
  id: '/api/story',
  path: '/api/story',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiImageServerRoute = ApiImageServerRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/image': typeof ApiImageServerRoute
  '/api/story': typeof ApiStoryServerRoute
}
export interface FileServerRoutesByTo {
  '/api/image': typeof ApiImageServerRoute
  '/api/story': typeof ApiStoryServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/image': typeof ApiImageServerRoute
  '/api/story': typeof ApiStoryServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/image' | '/api/story'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/image' | '/api/story'
  id: '__root__' | '/api/image' | '/api/story'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiImageServerRoute: typeof ApiImageServerRoute
  ApiStoryServerRoute: typeof ApiStoryServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/story': {
      id: '/api/story'
      path: '/api/story'
      fullPath: '/api/story'
      preLoaderRoute: typeof ApiStoryServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiImageServerRoute: ApiImageServerRoute,
  ApiStoryServerRoute: ApiStoryServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
